{"uuid": "4726e549-c764-4297-a24a-11abcc184f25", "children": ["03cf398c-5445-4822-b973-9cb4c5922335", "2145cd40-873a-4894-bedd-e5b81889ef1e"], "befores": [{"name": "beforeClass", "status": "broken", "statusDetails": {"message": "AttributeError: cls not available in module-scoped context\n", "trace": "  File \"/Users/nikhilsai/Desktop/Projects/python_testing/projects/mobile_testing/venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/nikhilsai/Desktop/Projects/python_testing/projects/mobile_testing/venv/lib/python3.9/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/nikhilsai/Desktop/Projects/python_testing/projects/mobile_testing/venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/nikhilsai/Desktop/Projects/python_testing/projects/mobile_testing/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/nikhilsai/Desktop/Projects/python_testing/projects/mobile_testing/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/nikhilsai/Desktop/Projects/python_testing/projects/mobile_testing/tests/conftest.py\", line 9, in beforeClass\n    if request.cls is not None:\n  File \"/Users/nikhilsai/Desktop/Projects/python_testing/projects/mobile_testing/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 445, in cls\n    raise AttributeError(f\"cls not available in {self.scope}-scoped context\")\n"}, "start": 1722876772773, "stop": 1722876779710}], "start": 1722876772773, "stop": 1722876779749}